#ifndef PROTOCOL_H
#define PROTOCOL_H

#define HANDSHAKE_STRING "C64_CHAT_READY\r\n"
#define CONNECTED_STRING "CONNECTED\r\n"
#define EOF_CHAR 0x04
#define CR_CHAR 0x0D
#define LF_CHAR 0x0A
#define BACKSPACE_CHAR 0x08
#define DELETE_CHAR 0x7F

#define MAX_INPUT_LENGTH 255
#define BAUD_RATE_2400 2400

#define SERIAL_BUFFER_SIZE 256
#define INPUT_BUFFER_SIZE 256

#endif